// =============================================================================
// Testbench: tb_acc_hex
// Purpose:
//   Read input_A.hex / input_B.hex / golden_sum.hex generated by
//   generate_golden.py and verify the acc datapath block by block.
//
// Python defaults:
//   Mblocks = 5, N = 10, DATAwidthIDTH = 8
//   golden_sum.hex contains one final MAC sum per block.
// =============================================================================
`timescale 1ns/1ps

module tb_mac_accum;

    // Keep these values consistent with tb_mac_top.sv and generate_golden.py.
    localparam integer Mblocks = 5;
    localparam integer N = 10;
    localparam integer Awidth = 8;
    localparam integer Bwidth = 8;
    localparam integer Accwidth = 32;
    localparam integer Clkperiod = 8;
    localparam integer Totaldata = Mblocks * N;

    localparam string Ahexfile = "input_A.hex";
    localparam string Bhexfile = "input_B.hex";
    localparam string Goldenhexfile = "golden_sum.hex";

    // DUT inputs/outputs use the same naming as mac_accum.sv.
    reg i_clk;
    reg i_rst_n;
    reg i_acc_en;
    reg i_acc_clr;
    reg  [Awidth-1:0] i_A_data;
    reg  [Bwidth-1:0] i_B_data;
    wire [Accwidth-1:0] o_acc_sum_r;

    reg [Awidth-1:0] a_mem [Totaldata];
    reg [Bwidth-1:0] b_mem [Totaldata];
    reg [Accwidth-1:0] gold_mem [Mblocks];

    integer error_count;
    integer pass_count;
    integer file_error_count;
    integer blk;
    integer idx;

    // -------------------------------------------------------------------------
    // DUT: mac_accum.sv
    // -------------------------------------------------------------------------
    mac_accum #(
        .Awidth   (Awidth),
        .Bwidth   (Bwidth),
        .Accwidth (Accwidth)
    ) dut (
        .i_clk       (i_clk),
        .i_rst_n     (i_rst_n),
        .i_acc_en    (i_acc_en),
        .i_acc_clr   (i_acc_clr),
        .i_A_data    (i_A_data),
        .i_B_data    (i_B_data),
        .o_acc_sum_r (o_acc_sum_r)
    );

    initial i_clk = 1'b0;
    always #(Clkperiod/2) i_clk = ~i_clk;

    // Clear accumulator with i_acc_clr only.
    task automatic clear_accumulator;
        begin
            @(negedge i_clk);
            i_acc_en  = 1'b0;
            i_acc_clr = 1'b1;

            @(posedge i_clk);
            #1;
            if (o_acc_sum_r !== {Accwidth{1'b0}}) begin
                error_count = error_count + 1;
                $display("[%0t] FAIL: clear, DUT sum = 0x%08h",
                         $time, o_acc_sum_r);
            end

            @(negedge i_clk);
            i_acc_clr = 1'b0;
        end
    endtask

    task automatic check_block;
        input integer block_idx;
        begin
            if (o_acc_sum_r === gold_mem[block_idx]) begin
                pass_count = pass_count + 1;
                $display("[%0t] PASS: Block %0d  DUT=0x%08h  Golden=0x%08h",
                         $time, block_idx,
                         o_acc_sum_r, gold_mem[block_idx]);
            end else begin
                error_count = error_count + 1;
                $display("[%0t] FAIL: Block %0d  DUT=0x%08h  Golden=0x%08h",
                         $time, block_idx,
                         o_acc_sum_r, gold_mem[block_idx]);
            end
        end
    endtask

    initial begin
        i_rst_n          = 1'b0;
        i_acc_en         = 1'b0;
        i_acc_clr        = 1'b0;
        i_A_data         = {Awidth{1'b0}};
        i_B_data         = {Bwidth{1'b0}};
        error_count      = 0;
        pass_count       = 0;
        file_error_count = 0;

        // ---------------------------------------------------------------------
        // Read Python-generated stimulus and golden data.
        // ---------------------------------------------------------------------
        $display("[%0t] Loading %s, %s, %s",
                 $time, Ahexfile, Bhexfile, Goldenhexfile);

        $readmemh(Ahexfile,      a_mem);
        $readmemh(Bhexfile,      b_mem);
        $readmemh(Goldenhexfile, gold_mem);

        // Check whether any expected file entries stayed unknown.
        for (idx = 0; idx < Totaldata; idx = idx + 1) begin
            if (^a_mem[idx] === 1'bx) begin
                file_error_count = file_error_count + 1;
                $display("FILE ERROR: a_mem[%0d] is X", idx);
            end
            if (^b_mem[idx] === 1'bx) begin
                file_error_count = file_error_count + 1;
                $display("FILE ERROR: b_mem[%0d] is X", idx);
            end
        end

        for (blk = 0; blk < Mblocks; blk = blk + 1) begin
            if (^gold_mem[blk] === 1'bx) begin
                file_error_count = file_error_count + 1;
                $display("FILE ERROR: gold_mem[%0d] is X", blk);
            end
        end

        if (file_error_count != 0) begin
            $display("\nTEST ABORTED: %0d HEX FILE ERROR(S)", file_error_count);
            $finish;
        end

        // ---------------------------------------------------------------------
        // Reset DUT.
        // mac_accum.sv currently implements active-low async reset.
        // ---------------------------------------------------------------------
        repeat (3) @(posedge i_clk);
        @(negedge i_clk);
        i_rst_n = 1'b1;

        @(posedge i_clk);
        #1;
        if (o_acc_sum_r !== {Accwidth{1'b0}}) begin
            error_count = error_count + 1;
            $display("[%0t] FAIL: reset check, DUT sum = 0x%08h",
                     $time, o_acc_sum_r);
        end

        // ---------------------------------------------------------------------
        // Each Python block contains N pairs. Clear, accumulate N times,
        // then compare the accumulator output against golden_sum.hex.
        // ---------------------------------------------------------------------
        for (blk = 0; blk < Mblocks; blk = blk + 1) begin
            $display("\n---- Block %0d: clear + accumulate %0d pairs ----", blk, N);

            clear_accumulator();

            for (idx = 0; idx < N; idx = idx + 1) begin
                @(negedge i_clk);
                i_A_data = a_mem[blk*N + idx];
                i_B_data = b_mem[blk*N + idx];
                i_acc_en = 1'b1;

                @(posedge i_clk);
                #1;
            end

            @(negedge i_clk);
            i_acc_en = 1'b0;

            check_block(blk);

            // Hold check: output must not change when both control inputs are 0.
            @(posedge i_clk);
            #1;
            if (o_acc_sum_r !== gold_mem[blk]) begin
                error_count = error_count + 1;
                $display("[%0t] FAIL: hold check Block %0d, DUT=0x%08h Golden=0x%08h",
                         $time, blk, o_acc_sum_r, gold_mem[blk]);
            end
        end

        $display("\n==========================================================");
        if (error_count == 0)
            $display("ALL %0d BLOCKS PASSED (tb_acc -> mac_accum)", pass_count);
        else
            $display("%0d BLOCK(S) PASSED, %0d ERROR(S) (tb_acc -> mac_accum)",
                     pass_count, error_count);
        $display("==========================================================");

        $finish;
    end

endmodule
